//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AttributePrefixes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttributePrefixes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Space.AttributePrefixes", typeof(AttributePrefixes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedy.
        /// </summary>
        public static string AccelerationForce {
            get {
                return ResourceManager.GetString("AccelerationForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenable.
        /// </summary>
        public static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energetic.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enduring.
        /// </summary>
        public static string EnergyRegeneration {
            get {
                return ResourceManager.GetString("EnergyRegeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vital.
        /// </summary>
        public static string HealthRegeneration {
            get {
                return ResourceManager.GetString("HealthRegeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotating.
        /// </summary>
        public static string RotationForce {
            get {
                return ResourceManager.GetString("RotationForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farseeing.
        /// </summary>
        public static string SensorRange {
            get {
                return ResourceManager.GetString("SensorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protective.
        /// </summary>
        public static string ShieldEfficiency {
            get {
                return ResourceManager.GetString("ShieldEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modest.
        /// </summary>
        public static string ShieldEnergyConsumption {
            get {
                return ResourceManager.GetString("ShieldEnergyConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic.
        /// </summary>
        public static string ThrusterEnergyConsumption {
            get {
                return ResourceManager.GetString("ThrusterEnergyConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relentless.
        /// </summary>
        public static string WeaponCooldown {
            get {
                return ResourceManager.GetString("WeaponCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient.
        /// </summary>
        public static string WeaponEnergyConsumption {
            get {
                return ResourceManager.GetString("WeaponEnergyConsumption", resourceCulture);
            }
        }
    }
}
