//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Space.ItemNames", typeof(ItemNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Reactor.
        /// </summary>
        public static string BasicReactor {
            get {
                return ResourceManager.GetString("BasicReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Sensor.
        /// </summary>
        public static string BasicSensor {
            get {
                return ResourceManager.GetString("BasicSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Shield.
        /// </summary>
        public static string BasicShield {
            get {
                return ResourceManager.GetString("BasicShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Thruster.
        /// </summary>
        public static string BasicThruster {
            get {
                return ResourceManager.GetString("BasicThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Weapon.
        /// </summary>
        public static string BasicWeapon {
            get {
                return ResourceManager.GetString("BasicWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Reactor.
        /// </summary>
        public static string CommonBasicReactor {
            get {
                return ResourceManager.GetString("CommonBasicReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Sensor.
        /// </summary>
        public static string CommonBasicSensor {
            get {
                return ResourceManager.GetString("CommonBasicSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Shield.
        /// </summary>
        public static string CommonBasicShield {
            get {
                return ResourceManager.GetString("CommonBasicShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Thruster.
        /// </summary>
        public static string CommonBasicThruster {
            get {
                return ResourceManager.GetString("CommonBasicThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Weapon.
        /// </summary>
        public static string CommonBasicWeapon {
            get {
                return ResourceManager.GetString("CommonBasicWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Reactor.
        /// </summary>
        public static string PoorBasicReactor {
            get {
                return ResourceManager.GetString("PoorBasicReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Sensor.
        /// </summary>
        public static string PoorBasicSensor {
            get {
                return ResourceManager.GetString("PoorBasicSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Shield.
        /// </summary>
        public static string PoorBasicShield {
            get {
                return ResourceManager.GetString("PoorBasicShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Thruster.
        /// </summary>
        public static string PoorBasicThruster {
            get {
                return ResourceManager.GetString("PoorBasicThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Weapon.
        /// </summary>
        public static string PoorBasicWeapon {
            get {
                return ResourceManager.GetString("PoorBasicWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Reactor.
        /// </summary>
        public static string RareBasicReactor {
            get {
                return ResourceManager.GetString("RareBasicReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Sensor.
        /// </summary>
        public static string RareBasicSensor {
            get {
                return ResourceManager.GetString("RareBasicSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Shield.
        /// </summary>
        public static string RareBasicShield {
            get {
                return ResourceManager.GetString("RareBasicShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Thruster.
        /// </summary>
        public static string RareBasicThruster {
            get {
                return ResourceManager.GetString("RareBasicThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Weapon.
        /// </summary>
        public static string RareBasicWeapon {
            get {
                return ResourceManager.GetString("RareBasicWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starter Reactor.
        /// </summary>
        public static string StarterReactor {
            get {
                return ResourceManager.GetString("StarterReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starter Sensor.
        /// </summary>
        public static string StarterSensor {
            get {
                return ResourceManager.GetString("StarterSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starter Shield.
        /// </summary>
        public static string StarterShield {
            get {
                return ResourceManager.GetString("StarterShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starter Thruster.
        /// </summary>
        public static string StarterThruster {
            get {
                return ResourceManager.GetString("StarterThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starter Weapon.
        /// </summary>
        public static string StarterWeapon {
            get {
                return ResourceManager.GetString("StarterWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Reactor.
        /// </summary>
        public static string UncommonBasicReactor {
            get {
                return ResourceManager.GetString("UncommonBasicReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Sensor.
        /// </summary>
        public static string UncommonBasicSensor {
            get {
                return ResourceManager.GetString("UncommonBasicSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Shield.
        /// </summary>
        public static string UncommonBasicShield {
            get {
                return ResourceManager.GetString("UncommonBasicShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Thruster.
        /// </summary>
        public static string UncommonBasicThruster {
            get {
                return ResourceManager.GetString("UncommonBasicThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Weapon.
        /// </summary>
        public static string UncommonBasicWeapon {
            get {
                return ResourceManager.GetString("UncommonBasicWeapon", resourceCulture);
            }
        }
    }
}
